spring:
  profiles:
    active: "dev"
---
spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: task-management-system
  jpa:
    hibernate:
      ddl-auto: validate
    #              ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/tms
    url: jdbc:postgresql://localhost:5433/tms
    username: tms
    password: tms
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog.xml
server:
  port: 8080
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  secret: im8476rgf8i7r6geue7wn6ergn76ergfs76wngrfiwuntrfbyt5rd6
  tokenExpiration: 15m

---
spring:
  config:
    activate:
      on-profile: "test"
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog-test.xml
jwt:
  secret: im8476r34f34f34geue7wn6ergn76ergfs76wngrfiwuntrfbyt5rd6
  tokenExpiration: 15m